#!/usr/bin/env bash
# checking parameters for file transfer
# 0-success, 1-error

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# asigning parameters to variables

path_to_file=$1
ip_address=$2
user_name=$3
path_to_ssh_key=$4

# disable strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking if the file transfer was successful

if [ $? -eq 0 ]
then
	echo "FILE TRANSFER SUCCESSFUL"
else
	echo "FILE TRANSFER NOT SUCCESSFUL"
