#!/usr/bin/env bash
# Check if the number of parameters is less than 4
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Use scp to transfer the file to the server's home directory
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"

# Check if the scp command was successful
if [ $? -eq 0 ]; then
  echo "File transferred successfully."
else
  echo "Failed to transfer the file."
  exit 1
fi
