#!/usr/bin/env bash
# installation of nginx

sudo apt-get update
sudo apt-get install nginx

# this is to enable the nginx to use the firewall
sudo ufw 'Nginx HTTP'
echo "Hello World!" | sudo -tee /var/www/html/index.html

# this is testing nginx configuration
sudo nginx -t
sudo service nginx reload
