#!/usr/bin/env bash
# installation of nginx

sudo apt-get update
sudo apt-get install nginx

sudo ufw 'Nginx HTTP' # this is to enable the Nginx to use the firewall
echo "Hello World!" | sudo -tee /var/www/html/index.html
# this is testing nginx configuration
sudo nginx -t
sudo service nginx reload
