#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom HTML file for Nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Enable the firewall rule for Nginx
sudo ufw allow 'Nginx HTTP'

# Check the configuration and restart Nginx to apply changes
sudo nginx -t
sudo service nginx restart
