#!/usr/bin/env bash
# Update and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Start Nginx service and allow it through the firewall
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Create a new configuration file for the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name journeytogreatness.tech www.journeytogreatness.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Enable the new configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default configuration link to avoid conflicts
sudo rm /etc/nginx/sites-enabled/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Customize the 404 page in the default Nginx configuration
sudo sed -i "s|listen 80 default_server;|listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}|" /etc/nginx/sites-enabled/redirect_me

# Test Nginx configuration and restart service
sudo nginx -t
sudo service nginx restart
