#!/usr/bin/env bash
# permanent redirection by performing 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start
sudo ufw allow  'Nginx HTTP' # this is to enable the Nginx to use the firewall

echo "Hello World!" | sudo tee /var/www/html/index.html

# Define the replacement string directly in the script
string_for_replacement='server_name _;rewrite ^/redirect_me https://github.com/stevovenom permanent;'

# Perform the replacement using sed
sudo sed -i "s|server_name _;|$string_for_replacement|" /etc/nginx/sites-enabled/default

string_for_replacement="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\tinternal;\n\t}"

# Perform the replacement using sed
sudo sed -i "s|listen 80 default_server;|$string_for_replacement|" /etc/nginx/sites-enabled/default

# create an error 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo nginx -t
sudo service nginx restart
