#!/usr/bin/env bash
# the trap signals define the corresponding actions
# we then get the PID of the script and store it in the pid_file
# desplay the To infinity and beyond indefinitely
pid_file="/var/run/myscript.pid"
trap 'echo "I hate the kill command";' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$pid_file"; exit 0' SIGQUIT SIGTERM
echo $$ > "$pid_file"
echo "To infinity and beyond indefinitely"
while true; do
	sleep 1
done
