#!/usr/bin/env bash
# The scipt displays Best School 9 tyimes and Hi then followed by Best School
i=1;
while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
